# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6045449ecd156455498b026d25d6fac18512af43c3305e79a1cec6ec33a3006c795a43a7855e96ca3591c37403381a8ccf08d123e64d0dd739a6fa5777117252

test:
  secret_key_base: e8a43e2cad825c1064f16c5cb9929d13ece4ba49e323b3e1b20d6f75197fd9138683b4d58cfd269a46d9ec3399d9e8efdec18c6a5b34cab43e5de6d9c8fe9410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
